### PR TITLE
Enable Halo pressed image in expanded status bar

### PR DESCRIPTION
**Pull request by manumanfred**
Title tells everything!
Tested on my ROM Dreams (CM Based) and works well!
Check the screenshots:
screenshot_2013-06-23-02-33-41

screenshot_2013-06-23-02-33-48

### CODE REVIEW

**Comment by aaronpoweruser** [comment]
The drawable is missing in this patch set

**Comment by manumanfred** [comment]
@aaronpoweruser  Sorry I don't really understand XML programmin language so what is missing?
It uses ic_notify_halo.xml which has information of normal and pressed image so it enables the presses image..
I checked how it the quick settings icon as pressed in CM repository and edited this carefully..

**Comment by spacecaker** [comment]
u are missing a png 
the pressed and normal png wich are needed

**Comment by manumanfred** [comment]
Seriously?
Those are included in ParanoidAndroid's frameworks/base repository, I haven't themed them!

**Pull request merged**
