### PR TITLE
Update PT-BR translations

### PR DESCRIPTION
**Pull request by ghost**
Commit for Nexus devices

### CODE REVIEW

**Comment by kaluoshi** [comment]
@gafanhotz we need to test them before, so do not re pull them if they are not merged yet :-)

**Comment by ghost** [comment]
@BigBrother1984 But I didn't re-pulled it. o.O I only pulled one for non-nexus devices on jellybean-legacy, this one I just changed the comment to "Nexus devices". wtf.

**Comment by kaluoshi** [comment]
@gafanhotz yeah i saw. i just said to not close them if they not got merged soon :+1:

**Comment by ghost** [comment]
@BigBrother1984 Well, I don't remember closing it either (maybe clicked on the wrong button here), but okay, I'll wait till your OK to submit new ones. ;)

**Pull request closed without merging**
