### PR TITLE
Enable Bare style PIE on protected lock screen

### PR DESCRIPTION
**Pull request by Anu6is**
When using a protected lock screen, PIE is usually disabled and there are no navigation controls in the lock screen camera or emergency dialer. This allows for PIE controls without access to quick toggles or notifications (Bare PIE).   Tested on Mako

### CODE REVIEW

**Comment by kaluoshi** [comment]
That's interesting :) good idea. One thing, did you tried to bypass lockscreen with the menu button of pie?

**Comment by Anu6is** [comment]
Tested all buttons...none give access to the phone without first requesting
to be unlocked. The multitasking button does switch to clear all however.

**Comment by kaluoshi** [comment]
Sorry can you please explain better what does pressing the recents button? :)

**Comment by Anu6is** [comment]
When you press recents
recents

It changes to Clear All
clear all

**Comment by kaluoshi** [comment]
Ah ok so the recents menu should be under the lockscreen :) ok that's good, thanks (that was a bad issue using camera for ex.)

**Comment by Anu6is** [comment]
Yes, the menu is under the lock screen

**Comment by kaluoshi** [comment]
Sorry man i edited the comment later but i see you're answering from email :) i'm writing in this one: when unlocked Pie should come back to user defined style right?

**Comment by Anu6is** [comment]
Yes...pie returns to user defined style when unlocked :)

**Comment by kaluoshi** [comment]
ok merging :) an idea will be make recent button not visible cause it's not used, but it's a little minor thing not really necessary. Thanks.

**Pull request merged**
