### PR TITLE
Fix floating window activity result cancellation

### PR DESCRIPTION
**Pull request by corcoran**
Setting Intent.FLAG_ACTIVITY_NEW_TASK on _all_ floating window intents
will result in Android dropping activity results for non-new task
activities trying to get results back.

Cheers,
SlimRoms

Change-Id: Ib125bd03733dc73859f7426150110d88319f7625

### CODE REVIEW

**Comment by aaronpoweruser** [comment]
Do you have a case where FLAG_ACTIVITY_NEW_TASK is harmful

**Comment by corcoran** [comment]
Yes and it happens often.  Examples would be say the Settings where you go to choose an icon and it loads up Gallery.  What happens right now is Gallery will return and the parent will ignore the result because the gallery was loaded with FLAG_ACTIVITY_NEW_TASK.

You can easily reproduce it w/ KeePassDroid.  Without this patch it won't get past the password dialog page.

**Comment by aaronpoweruser** [comment]
This change breaks halo. Click on a g plus notification in halo. then outside of the window to close it and g plus will take you back to your feed. instead of exiting halo. It the previous task also isnt scalled for halo see 
screenshot_2013-07-13-12-57-37

**Comment by corcoran** [comment]
Looking into this.  Does G+ normally scale appropriately when loaded in Halo?  I've always had it cut off like in your screenshot when pinned & launched as a floating window.

**Comment by kaluoshi** [comment]
@aaronpoweruser i have the g+ cutted off even without this change dude

**Comment by aaronpoweruser** [comment]
Your right. Have you noticed any adverse changes with this?

**Comment by aaronpoweruser** [comment]
Im going to merge this so others can test

**Pull request merged**
