### PR TITLE
HALO: Option to pause the underlying app (1/2)

### PR DESCRIPTION
**Pull request by tonyp**
DO NOT MERGE YET. Please try this out first.
I've been porting this over from my CM10.1 based Halo build.

This adds an option to pause the active app when using HALO.
I've enabled the option by default for devices with low memory. (Do you want that?)
I'm currently using the ActivityManager.isLargeRAM() function which will return true if the device got at least 640MB RAM available to the kernel.

I can customize / enable / disable the default behaviour if you'd like.
But I think it makes sense not to use two foreground activities on older devices which don't have enough RAM (at least by default, users can still change the option if they want).

Please give me some feedback - what do you guys think? :)

Cheers,
tonyp

### CODE REVIEW

**Comment by aaronpoweruser** [comment]
I like it

**Comment by tonyp** [comment]
:-)

**Comment by tpoint75** [comment]
Great idea!

**Comment by johnhany97** [comment]
Looks good ! Nice Idea !

**Comment by SferaDev** [comment]
Sounds good!

**Comment by kaluoshi** [comment]
Thanks @tonyp  :-)

**Pull request merged**
