### PR TITLE
Add LTE QS tile (1/2) and DSPManager build error fix

### PR DESCRIPTION
**Pull request by fairct**
The LTE tile was cherry-picked from CM. Corrected a few misspellings.

Also adds the settings piece to allow building of DSPManager.

### CODE REVIEW

**Comment by evan-a-a** [comment]
Also incomplete. Missing drawables and strings.

**Comment by fairct** [comment]
You're right. They got lost in my branch shuffling.

**Comment by fairct** [comment]
Did some looking, those files that weren't committed by me ALREADY EXIST in the PA repos. So... look again :) Looks like they weren't removed even though they're unused? I used this to find all the files that were added: http://review.cyanogenmod.org/#/c/32914/ but they're already here: https://github.com/ParanoidAndroid/android_frameworks_base/blob/jb43/packages/SystemUI/res/drawable-xhdpi/ic_qs_lte_off.png

**Comment by kaluoshi** [comment]
Cherry-picked only Quick Settings one, DSP abandoned for nexus', looking for kernel sound patches.

**Pull request closed without merging**
