### PR TITLE
Fix: ic_notify_halo => ic_notify_halo_normal

### PR DESCRIPTION
**Pull request by axsddlr**
reference to this: https://github.com/ParanoidAndroid/android_frameworks_base/commit/8d8e18a6f848e6319ca0fc742505971a6e2a3646

caused this error: frameworks/base/packages/SystemUI/res/layout/status_bar_expanded_header.xml:87: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/ic_notify_halo').

Signed-off-by: ayysir dresadd09691@gmail.com

### CODE REVIEW

**Comment by alteredlikeness** [comment]
I compiled fine last night for legacy - make clobber'ed, repo sync'ed, and built with no errors..
But.. (this is a big but, hence the pause:) I have been getting SystemUI FC's on my last few builds.. and have not really tried to track it down yet. The logs point to SystemUI, but could it be because I switched to the jellybean-legacy system/core..is that not ready yet?
Anyway, here's a log snippet (from last night's build): http://pastebin.com/9hjJS02H - and here's a totally different log from a couple days ago, same SysUI FC's: http://pastebin.com/LU2UMCf8

**Comment by axsddlr** [comment]
didnt this pull request was a big deal. but seems so

**Comment by alteredlikeness** [comment]
:D mountains are made from molehills daily.. but I also have not ran into that status_bar_expanded_header error that you got.

**Comment by axsddlr** [comment]
I'll just close the pull request and keep it in my own builds. Because make clobber and building does not fix this error unless I have this commit

**Pull request closed without merging**
